### ISSUE TITLE
vc3-pilot progressive output

### ISSUE THREAD

**Issue by dthain** [vc3-project/vc3-builder#1]
Some suggested output for the pilot job, as it works, so that the user can quickly grasp the principle of operation:

```
checking for installed parrot: not installed
parrot requires cvmfs-1.2.3
cvmfs-1.2.3 requires cmake-1.2.3
checking for installed cmake: not installed
downloading cmake from $url ...
building cmake
installing cmake
. . .
```

Also suggest that you redirect the stderr of the various procedures, so that the output isn't overwhelmed by information that is out of context.  (Builds like to emit a lot of stuff on stderr.)

**Comment by btovar** [comment]
Fixed by  2f7b67e
