### ISSUE TITLE
LibCVMFS Build Error

### ISSUE THREAD

**Issue by nhazekam** [vc3-project/vc3-builder#10]
While building CCTools in vagrant for singularity.

[100%] Built target libcvmfs
+ : Wed Nov 8 00:35:52 2017
+ mkdir -p /vc3-builder/vc3-root/x86_64/generic/libcvmfs/v2.3.0/{lib,include}
+ : Wed Nov 8 00:35:52 2017
+ cp libcvmfs.a /vc3-builder/vc3-root/x86_64/generic/libcvmfs/v2.3.0/lib
+ : Wed Nov 8 00:35:52 2017
+ cp ../../cvmfs/libcvmfs.h ../../cvmfs/libcvmfs_int.h /vc3-builder/vc3-root/x86_64/generic/libcvmfs/v2.3.0/include
cp: target '/vc3-builder/vc3-root/x86_64/generic/libcvmfs/v2.3.0/include' is not a directory
Cleaning payload with pid: 8405

I am building this in an 

Ubuntu:16.04

command:
    apt-get -y update
    apt-get -y install build-essential git libz-dev libperl-dev python-dev swig
    git clone https://github.com/vc3-project/vc3-builder.git
    cd vc3-builder
    ./vc3-builder --require cctools

**Comment by btovar** [comment]
Fixed in  ea40edb99145de18017eac65e2896e72f6150215
