### ISSUE TITLE
Misspelling of "writing"

### ISSUE THREAD

**Issue by nhazekam** [vc3-project/vc3-builder#8]
Word writing in error string is misspelled. 

https://github.com/vc3-project/vc3-builder/blob/2bb1cf30d4d792f696d20e415d7452b40c68a518/vc3-builder#L13867

https://github.com/vc3-project/vc3-builder/blob/2bb1cf30d4d792f696d20e415d7452b40c68a518/vc3-builder#L13879

**Comment by btovar** [comment]
Fixed in ea7ad08b55526f2c128aaf63686ba0bdbdd829b1
