### ISSUE TITLE
Create Singularity image using VC3 Builder

### ISSUE THREAD

**Issue by nhazekam** [vc3-project/vc3-builder#9]
Provide the steps to or a script that builds an image in a singularity using software built with VC3. Ideally this would be building and exporting the environment from VC3 builder into an image.

This would be great to reproducibly creating an image in different distros and across versions.

**Comment by btovar** [comment]
Documented in the README here:

https://github.com/vc3-project/vc3-builder#creating-container-images-with-a-vc3-builder-environment
